services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    volumes:
      - ./data/evaluations.json:/app/data/evaluations.json
    environment:
      - STREAMLIT_SERVER_PORT=8501